[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[flake8]
max-line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
ensure_newline_before_comments = true

[tool.black]
line-length = 79
target-version = ['py35', 'py36', 'py37', 'py38', 'py39', 'py310' ,'py311']
